repos:
- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
  - id: black
- repo: https://github.com/pycqa/pylint
  rev: v2.13.9
  hooks:
  - id: pylint
    language: system
    args:
      [
        "-rn", # Only display messages
      ]
