repos:
- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
    - id: isort
      name: isort (python)
- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
  - id: black
- repo: https://github.com/pycqa/pylint
  rev: v2.13.9
  hooks:
  - id: pylint
    language: system
    args:
      [
        "-rn", # Only display messages
      ]
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.960
  hooks:
  - id: mypy
    additional_dependencies: [types-requests==2.27.29]
