name: tests

on:
  push:
    branches: ["main"]
  pull_request: {}

concurrency:
  # If this was triggered from a pull request, only run one at a time and cancel any older,
  # in-progress runs.
  group: tests-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
      - name: Install dependencies
        run: poetry install
      - name: Run pytest
        run: poetry run pytest -v
